spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
auth:
  type: APACHE_DS # IN_MEMORY, APACHE_DS, ACTIVE_DIRECTORY
  ad:
    domain: my.domain.com
    url: ldap://my.domain.com:389/
    filter: (&(sAMAccountName={0})(objectclass=user))
  
logging:
  level:
    com:
      github:
        aha:
          poc:
            security: DEBUG
    org:
      springframework:
        security:
          ldap:
            authentication:
              ad: DEBUG